### ISSUE TITLE
Crash occured while experiencing 400 error

### ISSUE THREAD

**Issue by JiriTrecak** [algolia/algoliasearch-client-objc#11]
Hello guys,

our application just noticed crash in algolia search library and I was fortunate enough to have debugger plugged in, so I am sending the report to you.

Crash occured while basic query to one of the indexes we have in Algolia. We received 400 response (can't really tell why, never happened to us before) - then the crash occured:

ASAPIClient+Network.m
```objc
    AFHTTPRequestOperation *operation = [httpRequestOperationManager HTTPRequestOperationWithRequest:request success:^(AFHTTPRequestOperation *operation, id JSON) {
        if ((operation.response.statusCode / 100) == 2) {
            success(JSON);
        } else {
            failure(@"No error message");
        }
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        if ((operation.response.statusCode / 100) == 4) {
            NSData *errorData = error.userInfo[AFNetworkingOperationFailingURLResponseDataErrorKey];

           // Here, the crash occured, because errorData == nil
            NSDictionary *JSON = [NSJSONSerialization JSONObjectWithData: errorData options:kNilOptions error:nil];
            failure([NSString stringWithFormat:@"Bad request argument: %@", JSON[@"message"]]);
        } else {
            if ((index + 1) < [managers count]) {
                [self performHTTPQuery:path method:method body:body managers:managers index:(index + 1) timeout:(timeout + 10) success:success failure:failure];
            } else {
                failure(error.description);
            }
        }
    }];
```

When I went through the variables in debugger, here is what I got:
**(lldb) po error**
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (Unescaped control character around character 53.) UserInfo=0x171460d80 {NSDebugDescription=Unescaped control character around character 53., NSUnderlyingError=0x17024cea0 "Request failed: bad request (400)"}

**(lldb) po operation**
<AFHTTPRequestOperation: 0x1741cd890, state: isFinished, cancelled: NO request: <NSMutableURLRequest: 0x17420c160> { URL: https://AKEWZBYMIT-dsn.algolia.net/1/indexes/[OURINDEX]/query }, response: <NSHTTPURLResponse: 0x170824dc0> { URL: https://akewzbymit-dsn.algolia.net/1/indexes/[OURINDEX]/query } { status code: 400, headers {
    "Access-Control-Allow-Credentials" = false;
    "Access-Control-Allow-Headers" = "x-algolia-application-id, connection, origin, x-algolia-api-key, content-type, content-length, x-algolia-signature, x-algolia-usertoken, x-algolia-tagfilters, DNT, X-Mx-ReqToken, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Authorization, Accept";
    "Access-Control-Allow-Methods" = "GET, PUT, DELETE, POST, OPTIONS";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 91;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Wed, 29 Apr 2015 11:41:13 GMT";
    Server = nginx;
} }>

The bug is pretty obvious, AFNetworking did not provide their underlaying error so it crashed. I suspect it will be very rare, but it still should be conditioned in case it happens to somebody else.

Have a nice day and keep up good work!

**Comment by Nagriar** [comment]
Thanks @JiriTrecak! I'm going to release a new version in the coming days with this fix.
