### ISSUE TITLE
AFNetworking 3.0, what should we do?

### ISSUE THREAD

**Issue by dethi** [algolia/algoliasearch-client-objc#18]
This issue aims to open the discussion about AFNetworking 3.0. 

**Brief**: Currently, we use *AFHTTPRequestOperationManager* to manage the request. This class was [removed in AFNetworking 3.0](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS_Dev_Weekly_Issue_228#classes-removed). Instead, we should use the another class (*AFHTTPSessionManager*) which is already available in AFNetworking 2.0. This class use the new API of Apple: *NSURLSession* (available since iOS 7.0) instead of *NSURLConnection*.

**Pros:** Well, AFNetworking 3.0 officially supports iOS 7+, Mac OS X 10.9+, watchOS 2+, tvOS 9. Currently, our version of AFNetworking doesn't support tvOS :(

**Cons**: 
- there are maybe some clients that still need to [supports iOS 6](https://developer.apple.com/support/app-store/)?
- dependency issue for all the project that expect AFNetworking 2.x (if we update to 3.0)

**Comment by mrezk** [comment]
+1 on migrating to AFNetworking 3.0 and bumping to v4.0.0. Users who need support for iOS 6 or use AFNetworking 2.x can still use v3.6.3.

**Comment by JonathanBouaziz** [comment]
+1 on this

**Comment by khoren93** [comment]
+1 for AFNetworking 3.x support.

**Comment by AdamBCo** [comment]
+1 for AFNetworking 3.0 support!!

**Comment by clement-leprovost-algolia** [comment]
The Objective-C client is now deprecated in favor of the recently released [Swift client v3](https://github.com/algolia/algoliasearch-client-swift/releases/tag/3.0). This new Swift client has no dependency on AFNetworking (it just uses plain `NSURLSession`), so I guess this solves the problem. :)

As a consequence, there is no plan to migrate the Objective-C client to AFNetworking 3.

Please note that the Objective-C client will continue to receive bug fixes.
