### ISSUE TITLE
Disjunctive Faceting 

### ISSUE THREAD

**Issue by sohamchak** [algolia/algoliasearch-client-objc#22]
While I am working on advance search i am trying to use disjunctive faceting but not getting any idea how to implement it in objective c, as because I want to send multiple facet filtering data with “AND” and “OR” value together for algolia client search. Is it possible to do. Can you please tell me how.

**Comment by sohamchak** [comment]
Please Update disjunctive faceting for objective c. We need to launch our website ios app. We already got the android update of disjunctive faceting few weeks back.

**Comment by clement-leprovost-algolia** [comment]
We're very sorry, but there is currently no plan to implement the disjunctive faceting helper in the Objective-C client.
Please note, however, that disjunctive faceting will be implemented in the upcoming v3 of the Swift client, which will be usable from both Swift and Objective-C.

**Comment by clement-leprovost-algolia** [comment]
The Swift client's [version 3.0](https://github.com/algolia/algoliasearch-client-swift/releases/tag/3.0) has been released yesterday. Among the new features is disjunctive faceting.
