### ISSUE TITLE
Add a way to specify arbitrary query parameters

### ISSUE THREAD

**Issue by clement-leprovost-algolia** [algolia/algoliasearch-client-objc#25]
Add a way to specify query parameters by name and string value. This is intended as an untyped, low-level accessors to bypass limitations of the `Query` class (e.g. unsupported parameters).

*Note: this is a backport of a feature already implemented in the upcoming v3 of the Swift client.*

*Remark: Solving this issue would automatically fix #23 and #24.*

**Comment by sharad1404** [comment]
Our entire implementation is in obj-c. We have a need to set minimumAroundRadius, but we are stuck as we are not finding any docs to set this in obj-c. Can you please help guide us how to set this in obj-c.
