### ISSUE TITLE
searchDisjunctiveFaceting function unavailable in ObjC API version 3.5

### ISSUE THREAD

**Issue by SyedIsmailAhamed** [algolia/algoliasearch-client-objc#29]
Hi,
I was trying to a disjunctive search using objective c API, when i searched through the api documentation, i found this

Query* query = [[Query alloc] initWithQuery:@"luxury"];
query.facets = @[@"facilities", @"stars"];
NSDictionary* refinements = @{
    @"facilities": @[@"wifi"],
    @"stars": @[@"4", @"5"]
};
[index searchDisjunctiveFaceting:query disjunctiveFacets:@[@"stars"] refinements:refinements completionHandler:^(NSDictionary* content, NSError* error) {
    // [...]
}];

but when i try writing the code the function  searchDisjunctiveFaceting doesn't appear.

**Comment by clement-leprovost** [comment]
@SyedIsmailAhamed This Objective-C API client is [deprecated](https://github.com/algolia/algoliasearch-client-objc/#warning---deprecated) (has been for several months, now).

All Objective-C samples from the documentation (like the [Filtering & Faceting](https://www.algolia.com/doc/guides/search/filtering-faceting#faceting) guide to which you are probably referring) actually use the [Swift API client](https://github.com/algolia/algoliasearch-client-swift/). Note that you can still code in Objective-C and use the Swift client; we went to great lengths to ensure that.

There was indeed no disjunctive faceting in the legacy Objective-C client, and there will never be, as this project only receives critical bug fixes.

So my best advice is to migrate to our Swift client. It should be rather straightforward. Furthermore, there is a [Migration guide](https://github.com/algolia/algoliasearch-client-swift/wiki/Migration-guide-from-Objective-C-to-Swift-API-Client) to help you in this process.

**Comment by SyedIsmailAhamed** [comment]
Thanks,I managed to to use Swift API client in objective c, but am not getting how do i initialise index object.

**Comment by SyedIsmailAhamed** [comment]
/// A proxy to an Algolia index.
///
/// You cannot construct this class directly. Please use <code>Client.getIndex()
/// </code> to obtain an instance.

am unable to get  Client.getIndex()

**Comment by clement-leprovost** [comment]
@SyedIsmailAhamed What do you mean by "unable"?

This code should compile fine with version 3.x:

```
Client* client = [[Client alloc] initWithAppID:@"YOUR_APP_ID" apiKey:@"YOUR_API_KEY"];
Index* index = [client getIndex:@"YOUR_INDEX_NAME"];
```
... as can be seen in our [Objective-C demo](https://github.com/algolia/algolia-objc-demo/blob/add402a9f51f62e73d6ba69465697ae70f7d15a3/Source/MovieTableViewController.m#L71).

**Warning:** If you use the latest version of the Swift client (4.0), `Client.getIndex(_:)` is now `Client.index(withName:)` (`-[Client indexWithName:]` in Objective-C).
