### ISSUE TITLE
deleteByQuery is missing

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-objc#5]

**Comment by seafoox** [comment]
Please make sure that in the case the distinct is enabled on the index (with distinct > 1), we  `distinct=false` at query time, so the number of hits won't be > 1000. Otherwise, it will returns the following error: 

```
{
  "message": "invalid distinct value, hitsPerPage * distinct should be <= 1000",
  "status": 400
}
```

**Comment by clement-leprovost-algolia** [comment]
The Objective-C API client is now deprecated in favor of the recently released [Swift client v3](https://github.com/algolia/algoliasearch-client-swift/releases/tag/3.0). The Objective-C client will not receive any new features. It will, however, continue to receive bug fixes.
