### ISSUE TITLE
Disallow to change applicationID

### ISSUE THREAD

**Issue by dethi** [algolia/algoliasearch-client-objc#6]
Commit 73a3c7f20f57d0e0094d116ef0b8a37f583be351 allow the user to change the applicationID after the initialisation of ASAPClient. I think this is not a good idea, because in this case the header are changed but not the generated hostname. 

And we can't auto-generate the new hostname. Indeed, the user has maybe the DSN option or uses only one host.

**Comment by redox** [comment]
Indeed, changing the applicationID doesn't make sense. We started by doing it for the tagFilters and just do the same patch for the other properties. Regarding the API Key, it's probably the same. If we remove those methods; we'll need to bump to major version to Y of the X.Y.Z version to avoid any issue while upgrading.

**Comment by dethi** [comment]
Okey, so I will bump to 3.3.0 :smiley:
