### ISSUE TITLE
Is there a swift library available?

### ISSUE THREAD

**Issue by grantkemp** [algolia/algoliasearch-client-objc#8]
Do you guys have an eta for a swift library? or a tutorial for using the Objective c via a bridging header?

**Comment by dethi** [comment]
Yes of course, you can find it here: https://github.com/algolia/algoliasearch-client-swift
If you need some help, don't hesitate to contact me.

**Comment by redox** [comment]
We'll integrate it in our website documentation very soon @grantkemp. Let us know what you think!

**Comment by grantkemp** [comment]
Thanks guys, I will share feedback to Alex on your team
